FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y sudo
RUN apt-get install -y build-essential wget gcc-arm-linux-gnueabi git

RUN mkdir /go_installers
WORKDIR /go_installers
RUN wget https://dl.google.com/go/go1.21.5.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz

WORKDIR /

ENV PATH="${PATH}:/usr/local/go/bin"
