FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y sudo
RUN apt-get install -y build-essential wget gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu git

RUN mkdir /go_installers
WORKDIR /go_installers
RUN wget https://golang.org/dl/go1.21.5.linux-arm64.tar.gz
RUN tar -C /usr/local -xzf go1.21.5.linux-arm64.tar.gz

WORKDIR /

ENV PATH="${PATH}:/usr/local/go/bin"
